/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projet_threes;

/**
 *
 * @author mloub
 */
public class Fenetre_Accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fenetre_Accueil.class.getName());

    /**
     * Creates new form Fenetre_Accueil
     */
    public Fenetre_Accueil() {
        initComponents();
    }

    private void lancerJeu() {
        FenetreJeu jeuInterface = new FenetreJeu();
        jeuInterface.setVisible(true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        bouton_lancer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_intro.setText("THREES");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        bouton_lancer.setText("LANCER");
        bouton_lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_lancerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_lancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_lancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_lancerActionPerformed
        lancerJeu();
    }//GEN-LAST:event_bouton_lancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fenetre_Accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_lancer;
    private javax.swing.JLabel texte_intro;
    // End of variables declaration//GEN-END:variables
}
