/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projet_threes;
import java.util.logging.Level;
/**
 *
 * @author mloub
 */
public class FenetreFin_Jeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreFin_Jeu.class.getName());
    private int score;
    /**
     * Creates new form FenetreFin_Jeu
     */

    public FenetreFin_Jeu(int score) {
        initComponents();
        this.score = score;

        texte_fin.setText("GAME OVER");
        texte_score.setText("Votre score est de : " + score);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_fin = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_fin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_fin.setText("jLabel1");
        getContentPane().add(texte_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 100, 60));

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        texte_score.setText("jLabel1");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        try {
            Fenetre_Accueil accueil = new Fenetre_Accueil();
            accueil.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Impossible d'ouvrir FenetreAccueil", ex);
        }
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JLabel texte_fin;
    private javax.swing.JLabel texte_score;
    // End of variables declaration//GEN-END:variables
}
