/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projet_threes;

import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author scham
 */
public class FenetreJeu extends javax.swing.JFrame {
    private Jeu jeu ; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreJeu.class.getName());

    private JPanel panelGrille;
    private JLabel[] cases;

    /**
     * Creates new form FenetreJeu
     */
    public FenetreJeu() {
        initComponents();
        this.getContentPane().setLayout(new java.awt.BorderLayout());

        // Création du panel 4x4
        panelGrille = new JPanel();
        panelGrille.setLayout(new java.awt.GridLayout(4, 4, 5, 5)); // 4 lignes, 4 colonnes, gaps 5px

        cases = new JLabel[16];

        for (int i = 0; i < 16; i++) {
        cases[i] = new JLabel("", javax.swing.SwingConstants.CENTER);
        cases[i].setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK));
        cases[i].setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        panelGrille.add(cases[i]);
        
        
        
        
}

// On ajoute le panel au centre du JFrame
    this.getContentPane().add(panelGrille, java.awt.BorderLayout.CENTER);

    jeu = new Jeu();
    jeu.ajouterTuile();
    jeu.ajouterTuile();

    mettreAJourGrille();

// On demande à Swing de recalculer la fenêtre
    this.revalidate();
    this.repaint();
  }  
 private void mettreAJourGrille() {
        int[][] g = jeu.getGrille();
        for (int i = 0; i < 16; i++) {
            int ligne = i / 4;
            int colonne = i % 4;
            int valeur = g[ligne][colonne];
            cases[i].setText(valeur == 0 ? "" : String.valueOf(valeur));
        }
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreJeu().setVisible(true));
    }

    private void mettreAJourGrille() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

